### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-zigbee:

### ISSUE THREAD

**Issue by edelmaca** [itsmepetrov/homebridge-zigbee#24]
Hello,
after installing homebridge-zigbee with

> sudo npm install -g homebridge-zigbee

> 
i started homebridge with

> sudo homebridge

> 
 and got this output.

>[2019-2-20 21:15:35] Loaded config.json with 3 accessories and 4 platforms.
[2019-2-20 21:15:35] ---
[2019-2-20 21:15:35] Loaded plugin: homebridge-config-ui-x
[2019-2-20 21:15:35] Registering platform 'homebridge-config-ui-x.config'
[2019-2-20 21:15:35] ---
[2019-2-20 21:15:37] Loaded plugin: homebridge-people
[2019-2-20 21:15:37] Registering platform 'homebridge-people.People'
[2019-2-20 21:15:37] Registering accessory 'homebridge-people.PeopleAccessory'
[2019-2-20 21:15:37] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2019-2-20 21:15:37] ---
[2019-2-20 21:15:37] Loaded plugin: homebridge-raspberrypi-temperature
[2019-2-20 21:15:37] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[2019-2-20 21:15:37] ---
[2019-2-20 21:15:37] Loaded plugin: homebridge-shelly
[2019-2-20 21:15:37] Registering platform 'homebridge-shelly.Shelly'
[2019-2-20 21:15:37] ---
[2019-2-20 21:15:39] Loaded plugin: homebridge-sonos
[2019-2-20 21:15:39] Registering accessory 'homebridge-sonos.Sonos'
[2019-2-20 21:15:39] ---
[2019-2-20 21:15:41] Loaded plugin: homebridge-weather-plus
[2019-2-20 21:15:41] Registering platform 'homebridge-weather-plus.WeatherPlus'
[2019-2-20 21:15:41] ---
[2019-2-20 21:15:42] Loaded plugin: homebridge-wol
[2019-2-20 21:15:42] Registering accessory 'homebridge-wol.NetworkDevice'
[2019-2-20 21:15:42] ---
[2019-2-20 21:15:42] ====================
[2019-2-20 21:15:42] ERROR LOADING PLUGIN homebridge-zigbee:
[2019-2-20 21:15:42] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/build/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/build/Debug/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/build/Release/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/out/Debug/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/Debug/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/out/Release/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/Release/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/build/default/serialport.node
 → /usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/compiled/9.9.0/linux/arm/serialport.node
    at bindings (/usr/local/lib/node_modules/homebridge-zigbee/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/lib/bindings/linux.js:2:36)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee/node_modules/serialport/lib/bindings/auto-detect.js:16:22)
[2019-2-20 21:15:43] ====================
[2019-2-20 21:15:43] Loading 4 platforms...
[2019-2-20 21:15:43] [WeatherPlus] Initializing WeatherPlus platform...
[2019-2-20 21:15:43] [WeatherPlus] Initializing platform accessory 'Now'...
[2019-2-20 21:15:43] [Config] Initializing config platform...
[2019-2-20 21:15:43] [Config] Spawning homebridge-config-ui-x with PID 4004
[2019-2-20 21:15:43] [Shelly] Initializing Shelly platform...

>/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
            ^
Error: The requested platform 'ZigBeePlatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

> >

i don't know what all this has to say.
Before i installed the homebridge-zigbee plugin my homebridge was running fine. Maybe some of you know what to do on first sight. 😄 
i appreciate every tip and help.

**Comment by edelmaca** [comment]
Updated Node and NodeJS to the same Version number and it worked.
