### ISSUE TITLE
No Philips HUE Devices yet?

### ISSUE THREAD

**Issue by meinname** [itsmepetrov/homebridge-zigbee#25]
Hi, 
i got a Philips Hue White Wireless Dimming Kit and wanted to pair the Dimmer and the Lamp wit my zigbee stick.
But it seems it's not support by the homebrige-zigbee plugin yet.
First i tried it with the bulb.
This one i could pair.
Here the part of the zigbee.db - maybe you can add this one
`
{"id":2,"type":"Router","ieeeAddr":"0x0017880104a52db8","nwkAddr":53048,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","epList":[11,242],"status":"online","joinTime":1550834214,"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"manufacturerName":"Philips","modelId":"LWB010","dateCode":"20170908","powerSource":1,"swBuildId":"1.29.0_r21169"}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"currentLevel":254,"remainingTime":0}},"genOta":{"dir":{"value":2},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{"genGreenPowerProxy":{"dir":{"value":3},"attrs":{}}}}},"_id":"PnYbvhA0NBXeujul"}
{"$$deleted":true,"_id":"PnYbvhA0NBXeujul"}
`

But for the Dimmer i couldn't even pair. Do you know how to do this?
Model should be a RWL021

**Comment by meinname** [comment]
Update - haven't seen the reset switch in the back of the Dimmer ;)
Now paired this one too.
Here my db:
[zigbe.txt](https://github.com/itsmepetrov/homebridge-zigbee/files/2893962/zigbe.txt)

**Comment by meinname** [comment]
I tried to add support for the bulb with:

philips.hue.dimmable_bulb.js:
`
const HomeKitDevice = require('../HomeKitDevice')

class PhilipsDimmableBulb extends HomeKitDevice {
  static get description() {
    return {
      model: [
        'Philips LWB010',
      ],
      manufacturer: 'Philips',
      name: 'Philips HUE',
    }
  }

  getAvailbleServices() {
    return [{
      name: 'Bulb',
      type: 'Lightbulb',
    }]
  }

  onDeviceReady() {
    this.mountServiceCharacteristic({
      endpoint: 1,
      cluster: 'genOnOff',
      service: 'Bulb',
      characteristic: 'On',
      reportMinInt: 1,
      reportMaxInt: 300,
      reportChange: 1,
      parser: 'onOff',
    })
    this.mountServiceCharacteristic({
      endpoint: 1,
      cluster: 'genLevelCtrl',
      service: 'Bulb',
      characteristic: 'Brightness',
      reportMinInt: 1,
      reportMaxInt: 300,
      reportChange: 1,
      parser: 'dim',
    })
  }
}

module.exports = PhilipsDimmableBulb
`

but i get:
`
2019-2-22 14:41:10] [ZigBee] Unable to initialize device 0x0017880104a52db8, try to remove it and add it again.
[2019-2-22 14:41:10] [ZigBee] Reason: TypeError: Cannot read property 'report' of undefined
    at ZigBeeDevice.subscribe (/usr/local/lib/node_modules/homebridge-zigbee/lib/ZigBeeDevice.js:38:32)
    at PhilipsDimmableBulb.mountServiceCharacteristic (/usr/local/lib/node_modules/homebridge-zigbee/lib/HomeKitDevice.js:127:19)
    at PhilipsDimmableBulb.onDeviceReady (/usr/local/lib/node_modules/homebridge-zigbee/lib/devices/philips.hue.dimmable_bulb.js:22:10)
    at new HomeKitDevice (/usr/local/lib/node_modules/homebridge-zigbee/lib/HomeKitDevice.js:43:10)
    at new PhilipsDimmableBulb (/usr/local/lib/node_modules/homebridge-zigbee/lib/devices/philips.hue.dimmable_bulb.js:3:1)
    at ZigBeePlatform.initDevice (/usr/local/lib/node_modules/homebridge-zigbee/index.js:256:22)
    at ZigBeePlatform.handleZigBeeDevIncoming (/usr/local/lib/node_modules/homebridge-zigbee/index.js:156:12)
`

Sorry, i'm no coder so i don't know what i'm doing ;)

**Comment by giss69** [comment]
Hello,

is any news about support for Hue Phillips bulbs?

Thank you

**Comment by mysho87** [comment]
I created a new device (Philips LWB010) and it works fine with my HomeBrdige configuration:

Pull request:
https://github.com/itsmepetrov/homebridge-zigbee/pull/61
