### ISSUE TITLE
Ikea TRÅDFRI

### ISSUE THREAD

**Issue by Eranovmaxim** [itsmepetrov/homebridge-zigbee#3]
![photo_2018-10-23_16-25-51](https://user-images.githubusercontent.com/32778056/47509413-b93c0f00-d87e-11e8-9fc3-66b7bc51e98f.jpg)
Не появляются лампы Ikea TRÅDFRI 1000lm в приложении дом

**Comment by itsmepetrov** [comment]
This plugin currently doesn't support IKEA LED bulbs, only white

**Comment by itsmepetrov** [comment]
Any updates?

**Comment by Josch90** [comment]
Adding this would be awesome.

**Comment by Josch90** [comment]
> Sorry, I was wrong, it's not a colour bulb and I think we can add support for it very quickly: just try to add `'TRADFRI bulb E27 W opal 1000lm'` here https://github.com/itsmepetrov/homebridge-zigbee/blob/master/lib/devices/ikea.tradfri.bulb.js#L13

I've tried many versions with W and WS with and without spaces, but it is still an unrecognised device.

**Comment by itsmepetrov** [comment]
Please paste you model from logs here

**Comment by itsmepetrov** [comment]
Or attach your `zigbee.db` file

**Comment by Josch90** [comment]
Unrecognized device: 0x000b57fffe30f820 IKEA of Sweden TRADFRI bulbE27 opal 1000lm

{"id":7,"type":"Router","ieeeAddr":"0x000b57fffe30f820","nwkAddr":40641,"manufI$
{"id":7,"type":"Router","ieeeAddr":"0x000b57fffe30f820","nwkAddr":40641,"manufI$
{"id":7,"type":"Router","ieeeAddr":"0x000b57fffe30f820","nwkAddr":40641,"manufI$

**Comment by itsmepetrov** [comment]
Please attach db as a file

**Comment by Josch90** [comment]
[zigbee.db.zip](https://github.com/itsmepetrov/homebridge-zigbee/files/2668463/zigbee.db.zip)

**Comment by itsmepetrov** [comment]
Just try to add the following line: `TRADFRI bulb E27 opal 1000lm`

**Comment by Josch90** [comment]
Unrecognized device: 0x000b57fffe30f820 IKEA of Sweden TRADFRI bulbE27 opal 1000lm

**Comment by Josch90** [comment]
I've tried 
TRADFRI bulb E27 opal 1000lm
TRADFRI bulb E27 W opal 1000lm
TRADFRI bulb E27 WS opal 1000lm
TRADFRI bulb E27 Wopal 1000lm
TRADFRI bulb E27 WSopal 1000lm
none seems to be working.

**Comment by Josch90** [comment]
I always restarted the Homebridge server. is this enough or do i have to empty the device cachh and reconnect everything?

**Comment by itsmepetrov** [comment]
Try to add this one `TRADFRI bulbE27 opal 1000lm`

**Comment by Josch90** [comment]
[2018-12-11 20:03:46] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 1 of 10
[2018-12-11 20:03:46] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 2 of 10
[2018-12-11 20:03:47] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 3 of 10
[2018-12-11 20:03:47] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 4 of 10
[2018-12-11 20:03:48] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 5 of 10
[2018-12-11 20:03:48] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 6 of 10
[2018-12-11 20:03:48] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 7 of 10
[2018-12-11 20:03:49] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 8 of 10
[2018-12-11 20:03:49] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 9 of 10
[2018-12-11 20:03:50] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 10 of 10
[2018-12-11 20:03:50] [ZigBee] Device announced incoming and is added, id: 0x000b57fffe30f820
[2018-12-11 20:03:51] [ZigBee] Unrecognized device: 0x000b57fffe30f820 IKEA of Sweden TRADFRI bulbE27 opal 1000lm
[2018-12-11 20:04:36] [ZigBee] [RouterPolling] ping device: 0x000b57fffe30f820

The device is being pinged but not added

**Comment by itsmepetrov** [comment]
I think you are doing something wrong. From your logs I see that model name of your bulb is `TRADFRI bulbE27 opal 1000lm`, from database it's `TRADFRI bulb E27 opal 1000lm`. So make sure that you add this line in the right place, you can add some logs in the file to verify it.

**Comment by Josch90** [comment]
I added the line to this file: 
https://github.com/itsmepetrov/homebridge-zigbee/blob/master/lib/devices/ikea.tradfri.bulb.js#L13
 model: ['TRADFRI bulb E27 WSopal 980lm',
        'TRADFRI bulb E27 WS opal 980lm',
        'TRADFRI bulb E12 WS opal 400lm',
        'TRADFRI bulb E26 WS clear 950lm',
        'TRADFRI bulb E26 WS opal 980lm',
        'TRADFRI bulb E26 WSopal 980lm',
        'TRADFRI bulb E27 WS clear 950lm',
        'TRADFRI bulb E27 W opal 1000lm',
        'TRADFRI bulbE27 opal 1000lm',
        ]
Is there another place where I have to add it?

Is there something i have to reset?

**Comment by itsmepetrov** [comment]
Add this:

```js
if (Device.description.name === 'IKEA TRADFRI') {
  console.log('Available models:' Device.description.model)
  console.log('Device model:' model)
}
```

before this line https://github.com/itsmepetrov/homebridge-zigbee/blob/master/index.js#L233
and print logs

**Comment by itsmepetrov** [comment]
Any progress?

**Comment by Josch90** [comment]
where can i find the logs 🙈🙈🙈

**Comment by itsmepetrov** [comment]
How you got this logs?

```
[2018-12-11 20:03:46] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 1 of 10
[2018-12-11 20:03:46] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 2 of 10
```

**Comment by Josch90** [comment]
journalctl

**Comment by itsmepetrov** [comment]
So you should see it in `journalctl`

**Comment by Josch90** [comment]
[index.js.zip](https://github.com/itsmepetrov/homebridge-zigbee/files/2669326/index.js.zip)
I tried to find a log with locate this but i can't find it.

**Comment by itsmepetrov** [comment]
See my comment above

**Comment by Josch90** [comment]
Ok yes indeed you are right. Its not reading the Zigbee Plugin from /node_modules/homebridge-zigbee but from /home/pi/ZigBee/homebridge-zigbee/

this is the result i get now
```
[2018-12-11 21:58:42] [ZigBee] Unable to initialize device 0x000b57fffe30f820, try to remove it and add it again.
[2018-12-11 21:58:42] [ZigBee] Reason: TypeError: Cannot read property 'attrs' of undefined
    at IkeaTradfriBulb.onDeviceReady (/home/pi/ZigBee/homebridge-zigbee/lib/devices/ikea.tradfri.bulb.js:29:86)
    at new HomeKitDevice (/home/pi/ZigBee/homebridge-zigbee/lib/HomeKitDevice.js:49:10)
    at new IkeaTradfriBulb (/home/pi/ZigBee/homebridge-zigbee/lib/devices/ikea.tradfri.bulb.js:3:1)
    at ZigBeePlatform.initDevice (/home/pi/ZigBee/homebridge-zigbee/index.js:262:22)
    at ZigBeePlatform.handleZigBeeDevIncoming (/home/pi/ZigBee/homebridge-zigbee/index.js:159:12)
```

**Comment by itsmepetrov** [comment]
Good!

So as I understand this bulb supports only on/off and dim.

**Comment by Josch90** [comment]
yes 👍

**Comment by itsmepetrov** [comment]
I've created a new device description for you

Please undo all changes and put this file to `devices` folder: https://gist.github.com/itsmepetrov/6df7be02616ded7edc34b1598642c8ee

**Comment by itsmepetrov** [comment]
Thanks!

I'm going to add it to the package tomorrow.

**Comment by itsmepetrov** [comment]
Added in https://github.com/itsmepetrov/homebridge-zigbee/commit/9990ee0f27b2baa6137442c3fffbcf49e2d416b9
