### ISSUE TITLE
Instillation Issue

### ISSUE THREAD

**Issue by samuals151** [itsmepetrov/homebridge-zigbee#37]
I cant get this to install keep getting the following error:

41 error path git
42 error code ENOENT
43 error errno ENOENT
44 error syscall spawn git
45 error enoent Error while executing:
45 error enoent undefined ls-remote -h -t ssh://git@github.com/itsmepetrov/zcl-id.git
45 error enoent
45 error enoent
45 error enoent spawn git ENOENT
46 error enoent This is related to npm not being able to find a file.
47 verbose exit [ 1, true ]

**Comment by matzZz** [comment]
same here...

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/itsmepetrov/zcl-id.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by matzZz** [comment]
i have a solution.

you have to install git.
_sudo apt-get install git
and 
sudo usermod -a -G dialout homebridge_

then works fine.

**Comment by samuals151** [comment]
Yup that fixed it, although I also had to download the zip folder and add it manually but it runs correctly

Just doesn’t support my device after all that

**Comment by Olepir** [comment]
> Yup that fixed it, although I also had to download the zip folder and add it manually but it runs correctly
> 
> Just doesn’t support my device after all that

Which device you have?

**Comment by juancpin** [comment]
Folx, I updated git but it keeps saying on install:

> npm WARN deprecated homebridge-lib2.0.0: Latest version: 3.0.1
> npm WARN saveError ENOENT: no such file or directory, open '/home/juancpin/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/juancpin/package.json'
> npm WARN juancpin No description
> npm WARN juancpin No repository field
> npm WARN juancpin No README file
> npm WARN juancpin No license field

And then, if I try running homebridge (after adding "ZigBeePlatform" in config.json):

> [28/9/2019 19:04:39] Error: The requested platform 'ZigBeePlatform' was not registered by any plugin.
>     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
>     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
> 
> [28/9/2019 19:04:39] Got SIGTERM, shutting down Homebridge...
> 

Don't know what to do 😢

**Comment by rcaceiro** [comment]
I have the same problem
