### ISSUE TITLE
Gledopto GL-C-008S RGBCW controller and GL-B-008ZS  RGB bulb

### ISSUE THREAD

**Issue by Olepir** [itsmepetrov/homebridge-zigbee#46]
`
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b00193664b2","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1569667269,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"1CQ4f9cKALZPw5J4"}
{"id":2,"type":"EndDevice","ieeeAddr":"0x00158d0002c8f2f8","nwkAddr":28454,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,1026,1027,1029,65535],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"dir":{"value":3},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":2},"attrs":{}},"msTemperatureMeasurement":{"dir":{"value":1},"attrs":{}},"msPressureMeasurement":{"dir":{"value":1},"attrs":{}},"msRelativeHumidity":{"dir":{"value":1},"attrs":{}},"manuSpecificCluster":{"dir":{"value":3},"attrs":{}}}}},"_id":"XZU01kvazhTEqeVT"}
{"$$indexCreated":{"fieldName":"id","unique":true,"sparse":false}}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b00193664b2","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1569755452,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"1CQ4f9cKALZPw5J4"}
{"id":2,"type":"EndDevice","ieeeAddr":"0x00158d0002c8f2f8","nwkAddr":28454,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,1026,1027,1029,65535],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"dir":{"value":3},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":2},"attrs":{}},"msTemperatureMeasurement":{"dir":{"value":1},"attrs":{}},"msPressureMeasurement":{"dir":{"value":1},"attrs":{}},"msRelativeHumidity":{"dir":{"value":1},"attrs":{}},"manuSpecificCluster":{"dir":{"value":3},"attrs":{}}}}},"_id":"XZU01kvazhTEqeVT"}
{"id":3,"type":"Router","ieeeAddr":"0x00124b001d433e24","nwkAddr":31449,"manufId":0,"epList":[11,13],"status":"online","joinTime":1569765244,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"0dDk1i8143harlPQ"}
{"id":3,"type":"Router","ieeeAddr":"0x00124b001d433e24","nwkAddr":31449,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-008S","epList":[11,13],"status":"online","joinTime":1569765244,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"0dDk1i8143harlPQ"}
{"id":3,"type":"Router","ieeeAddr":"0x00124b001d433e24","nwkAddr":31449,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-008S","epList":[11,13],"status":"online","joinTime":1569765244,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}}}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{"lightLink":{"dir":{"value":3},"attrs":{}}}}},"_id":"0dDk1i8143harlPQ"}
{"id":4,"type":"Router","ieeeAddr":"0x00124b001eae058b","nwkAddr":60505,"manufId":0,"epList":[11,13],"status":"online","joinTime":1569769474,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"pei0d7hM9jFR8wWo"}
{"id":4,"type":"Router","ieeeAddr":"0x00124b001eae058b","nwkAddr":60505,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-B-008ZS","epList":[11,13],"status":"online","joinTime":1569769474,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"pei0d7hM9jFR8wWo"}
{"id":4,"type":"Router","ieeeAddr":"0x00124b001eae058b","nwkAddr":60505,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-B-008ZS","epList":[11,13],"status":"online","joinTime":1569769474,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}}}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{"lightLink":{"dir":{"value":3},"attrs":{}}}}},"_id":"pei0d7hM9jFR8wWo"}
`

**Comment by BobbyT** [comment]
you have multiple devices listed here. which one?

**Comment by Olepir** [comment]
> you have multiple devices listed here. which one?

There’s two devices from Gledopto: GL-C-008S RGBCW controller and GL-B-008ZS RGB bulb, I think it’s id3 and id4.

**Comment by BobbyT** [comment]
try this branch, maybe it will work... probably not

`npm i -g BobbyT/homebridge-zigbee#gledopto`

**Comment by Olepir** [comment]
> try this branch, maybe it will work... probably not

Bulb partially works – on/off and dimming, colour or white temperature selection not working
LED Controller not working at all
`[ZigBee] Unable to initialize device 0x00124b001d433e24, try to remove it and add it again.
[10/2/2019, 12:21:51 AM] [ZigBee] Reason: TypeError: Cannot read property 'getCharacteristic' of undefined
    at GledoptoRgbwCtrl.getServiceCharacteristic (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/lib/HomeKitDevice.js:126:7)
    at GledoptoRgbwCtrl.mountServiceCharacteristic (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/lib/HomeKitDevice.js:141:40)
    at GledoptoRgbwCtrl.onDeviceReady (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/lib/devices/gledopto.rgbw_ctrl.js:23:10)
    at new HomeKitDevice (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/lib/HomeKitDevice.js:49:10)
    at new GledoptoRgbwCtrl (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/lib/devices/gledopto.rgbw_ctrl.js:3:1)
    at ZigBeePlatform.initDevice (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/index.js:258:22)
    at ZigBeePlatform.handleZigBeeDevIncoming (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/index.js:158:12)`

**Comment by BobbyT** [comment]
redo the npm command, the controller might work now, for on and off.
colour temperature might take a while. the zigbee.db dump doesn't show any attributes for light control of your device.

**Comment by Olepir** [comment]
> redo the npm command, the controller might work now, for on and off.

Yes, looks like on/off is working.

> colour temperature might take a while. the zigbee.db dump doesn't show any attributes for light control of your device.

How can I help?

**Comment by BobbyT** [comment]
I added the colour temp code from another rgb lightbulb, maybe it works. redo the npm command

**Comment by Olepir** [comment]
> I added the colour temp code from another rgb lightbulb, maybe it works. redo the npm command

Colour temp is working for a bulb, RGB not working yet.
Can’t fully test LED controller now, I need to get some RGB+CCT LED strip for tests.

**Comment by BobbyT** [comment]
I think I have some colors working.... redo the npm cmd and test it please

**Comment by Olepir** [comment]
Working, but if I choose a colour a bulb blinks with pink (sometimes it’s a different colour, but mostly pink) and after that desired colour is set.

**Comment by Olepir** [comment]
Any updates?

**Comment by BobbyT** [comment]
sry... didn't have time. the code is mostly guess work, as I don't know how to debug this project.
