### ISSUE TITLE
homebridge-zigbee needs to be updated for Node v12

### ISSUE THREAD

**Issue by mrdc** [itsmepetrov/homebridge-zigbee#52]
Hello,

Looks like homebridge-zigbee plugin needs to be updated for Nove v12, as it causes errors after installation on docker-homebridge with Node v12.
Details:
https://github.com/oznu/docker-homebridge/issues/250

**Comment by mkellsy** [comment]
HOOBS runs on Node 12. I have a user that can't install the plugin. Here is the log output.

```
> serialport@6.2.2 install /Users/mkellsy/.hoobs/node_modules/serialport
> prebuild-install || node-gyp rebuild
...
../src/serialport.cpp:460:43: error: expected ';' after top level declarator
  void init(v8::Handle<v8::Object> target) {
                                          ^
                                          ;
12 warnings and 9 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/.hoobs/node_modules/serialport
gyp ERR!
 node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm
 WARN notsup Unsupported engine for concentrate@0.2.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.13.1","npm":"6.13.1"})
npm WARN notsup Not compatible with your version of node/npm: concentrate@0.2.3
npm WARN notsup Unsupported engine for dissolve@0.3.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.13.1","npm":"6.13.1"})
npm
WARN
 notsup Not compatible with your version of node/npm: dissolve@0.3.3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR!
 Exit status 1
npm
ERR!

npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm

ERR!
 A complete log of this run can be found in:
npm

ERR!
    ~/.npm/_logs/2019-11-27T17_10_20_764Z-debug.log
```

It looks like one of your deps is causing the issue serialport@6.2.2. There is a new version available 8.0.5, this seems to work in Node LTS.

**Comment by markus-fischbacher** [comment]
Upgrading serialport to 8.0.5 fixes the problem.
Would be nice, if the maintainer could do that for us.

**Comment by jonnycastaway** [comment]
I contacted the maintainer. He is a bit busy but will look at the problem next week. So i think he will contact us here 😉

**Comment by halilaykent** [comment]
I have the same problem too

**Comment by halilaykent** [comment]
hazar@hazar-Not-Specified:~$ npm i homebridge-zigbee

> serialport@6.2.2 install /home/hazar/node_modules/cc-znp/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.13.1 runtime=node arch=x64 platform=linux)
gyp WARN EACCES current user ("hazar") does not have permission to access the dev dir "/home/hazar/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
make: Entering directory '/home/hazar/node_modules/cc-znp/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:41:48: error: no matching function for call to ‘v8::Value::ToString()’
   v8::String::Utf8Value path(info[0]->ToString());
                                                ^
In file included from /tmp/.node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:48:53: error: no matching function for call to ‘v8::Value::ToObject()’
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /tmp/.node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterOpen(uv_work_t*)’:
../src/serialport.cpp:95:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:113:53: error: no matching function for call to ‘v8::Value::ToObject()’
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /tmp/.node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterUpdate(uv_work_t*)’:
../src/serialport.cpp:150:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterClose(uv_work_t*)’:
../src/serialport.cpp:188:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterFlush(uv_work_t*)’:
../src/serialport.cpp:231:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:250:53: error: no matching function for call to ‘v8::Value::ToObject()’
   v8::Local<v8::Object> options = info[1]->ToObject();
                                                     ^
In file included from /tmp/.node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/tmp/.node-gyp/12.13.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterSet(uv_work_t*)’:
../src/serialport.cpp:285:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:
../src/serialport.cpp:329:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
                                                                                                ^
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:330:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
                                                                                                ^
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:331:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
                                                                                                ^
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:336:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:
../src/serialport.cpp:378:106: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
                                                                                                          ^
In file included from /tmp/.node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /tmp/.node-gyp/12.13.1/include/node/v8.h:25,
                 from /tmp/.node-gyp/12.13.1/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/tmp/.node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/tmp/.node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:383:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function ‘void EIO_AfterDrain(uv_work_t*)’:
../src/serialport.cpp:424:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: At global scope:
../src/serialport.cpp:460:17: error: variable or field ‘init’ declared void
   void init(v8::Handle<v8::Object> target) {
                 ^~~~~~
../src/serialport.cpp:460:17: error: ‘Handle’ is not a member of ‘v8’
../src/serialport.cpp:460:34: error: expected primary-expression before ‘>’ token
   void init(v8::Handle<v8::Object> target) {
                                  ^
../src/serialport.cpp:460:36: error: ‘target’ was not declared in this scope
   void init(v8::Handle<v8::Object> target) {
                                    ^~~~~~
../src/serialport.cpp:460:36: note: suggested alternative: ‘tzset’
   void init(v8::Handle<v8::Object> target) {
                                    ^~~~~~
                                    tzset
In file included from ../../../../nan/nan.h:54:0,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
../src/serialport.cpp:485:25: error: ‘init’ was not declared in this scope
 NODE_MODULE(serialport, init);
                         ^
/tmp/.node-gyp/12.13.1/include/node/node.h:566:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(serialport, init);
 ^~~~~~~~~~~
../src/serialport.cpp:485:25: note: suggested alternative: ‘int’
 NODE_MODULE(serialport, init);
                         ^
/tmp/.node-gyp/12.13.1/include/node/node.h:566:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(serialport, init);
 ^~~~~~~~~~~
serialport.target.mk:112: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/home/hazar/node_modules/cc-znp/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hazar/node_modules/cc-znp/node_modules/serialport
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN notsup Unsupported engine for concentrate@0.2.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.13.1","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: concentrate@0.2.3
npm WARN notsup Unsupported engine for dissolve@0.3.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.13.1","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: dissolve@0.3.3
npm WARN enoent ENOENT: no such file or directory, open '/home/hazar/package.json'
npm WARN hazar No description
npm WARN hazar No repository field.
npm WARN hazar No README data
npm WARN hazar No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hazar/.npm/_logs/2019-12-16T21_50_56_851Z-debug.log

**Comment by DiPa2211** [comment]
I have the same problem. Did you find any other solution besides waiting for fixed version?

I tried to upgrade to serialport 8.0.6. However, that did not solve the problem

I installed serialport 8.0.6 and got this messages:

 `pi@raspberrypi:~ $ sudo npm install serialport --unsafe-perm --build-from-source`
 `serialport@8.0.6 postinstall /home/pi/node_modules/serialport`
 `node thank-you.js`
 `npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'`
 `npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'`
 `npm WARN pi No description`
 `npm WARN pi No repository field.`
 `npm WARN pi No README data`
 `npm WARN pi No license field.`
 ` + serialport@8.0.6`
 `updated 1 package and audited 553 packages in 3.965s`
 `found 0 vulnerabilities`


Now I don't know whether it has been installed successfully? Can you give me any hints?

**Comment by markus-fischbacher** [comment]
I‘m still waiting for the update 😉

**Comment by mkellsy** [comment]
You can downgrade Node to 10.17.0. It installs in this version.

**Comment by halilaykent** [comment]
@mkellsy But this time the homebridge config ui x wont work.

**Comment by jonnycastaway** [comment]
> You can downgrade Node to 10.17.0. It installs in this version.

That‘s not a solution if you use systems like Hoobs or a ready to go homebridge image.

The only right way is to actualize the plugin.

**Comment by mkellsy** [comment]
> @mkellsy But this time the homebridge config ui x wont work.

UI-X runs in 10.17.0, you need to uninstall it then reinstall it after you change the Node version.
```
sudo npm uninstall -g homebridge-config-ui-x
```

Then
```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by mkellsy** [comment]
> That‘s not a solution if you use systems like Hoobs or a ready to go homebridge image.
>
> The only right way is to actualize the plugin.

I make the HOOBS img file, and as of 3.1.9 we are using 10.17.0, because many plugins don't support Node 12 yet.

**Comment by markus-fischbacher** [comment]
For those, who installed Hoobs 3 with Node 12, what is the best way to downgrade?

**Comment by mkellsy** [comment]
We have a script for that.
```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/clean.sh | sudo bash -
```

**Comment by jonnycastaway** [comment]
Then i will test the downgrade after holidays.
Hope that all will work.

**Comment by markus-fischbacher** [comment]
@mkellsy the downgrade unfortunately broke my HOOBS installation. It's not booting anymore.
The cleanup script does not find npm.

```
main: line 66: npm: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
main: line 102: npm: command not found
main: line 103: npm: command not found
main: line 104: npm: command not found
Node  Installed
bash: line 188: npm: command not found
NPM Version 
Upgrading NPM
bash: line 195: npm: command not found
bash: line 196: npm: command not found
NPM  Installed
bash: line 206: npm: command not found
bash: line 207: npm: command not found

```

**Comment by mkellsy** [comment]
Run it again. I added the -k flag to the curl command that downloads Node

**Comment by markus-fischbacher** [comment]
Thanks, it worked! :)

**Comment by halilaykent** [comment]
Yes, Finally managed to make it work. However, my bulb was not a supperted device :(
Unrecognized device: 0x00158d0002c65f0d LUMI lumi.light.aqcn02

**Comment by jonnycastaway** [comment]
Puh, i downgrade with the Script and now my Hoobs 3 dies. Will check Logs later but no Hoobs UI at the moment 🙈

**Comment by jonnycastaway** [comment]
So, one day before christmas the maintainer release a new npm plugin: zigbee v2
I installed it and all is working.
If anyone will test ;-)

**Comment by markus-fischbacher** [comment]
@jonnycastaway nice 👍🏻 Which Zigbee adapter do you use?

**Comment by mrdc** [comment]
> 
> 
> So, one day before christmas the maintainer release a new npm plugin: zigbee v2
> I installed it and all is working.
> If anyone will test ;-)

Is it updatable via Homebridge GUI? Or manual installation?

**Comment by iGranDav** [comment]
https://www.npmjs.com/package/homebridge-zigbee-v2 has the same error for me :(

**Comment by markus-fischbacher** [comment]
I switched to RaspBee and homebridge-hue in combination with HOOBS.
It's working perfectly.

**Comment by BobbySlope** [comment]
Issue still exists, look like the installation fails on serialport install script.

Tried on Node 12.14.1 and 10.17.0

/tmp/.node-gyp/12.14.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../../nan/nan_object_wrap.h:65:61:   required from here
/tmp/.node-gyp/12.14.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [serialport.target.mk:110: Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/home/hoobs/.hoobs/node_modules/cc-znp/node_modules/serialport/build'
gyp ERR! build error
gyp ERR!
stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack
     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp
 ERR! System Linux 4.19.58-v7+
gyp ERR!
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/cc-znp/node_modules/serialport
gyp
 ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm
 WARN notsup Unsupported engine for concentrate@0.2.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.14.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: concentrate@0.2.3
npm WARN notsup Unsupported engine for dissolve@0.3.3: wanted: {"node":"~0.10.0"} (current: {"node":"12.14.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: dissolve@0.3.3
npm WARN
optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 (node_modules/node-aead-crypto):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 install: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm
ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BobbySlope** [comment]
serialport@6.2.2 is way behind. latest release 8.0.6 atm
everything lower than 8.0.0 is no longer supported

**Comment by clipse2004** [comment]
Any News for this? I use hoobs and today I bought a Zigbee Stick to integrate my Aqara things. But first we need a working plugin :)

**Comment by manuchis** [comment]
I updated serialport to v9.0.0 and still getting the same error.
