### ISSUE TITLE
Aqara Light Bulb

### ISSUE THREAD

**Issue by halilaykent** [itsmepetrov/homebridge-zigbee#56]
[12/28/2019, 11:10:44 AM] [ZigBee] Retrying connect to hardware
[12/28/2019, 11:10:51 AM] [ZigBee] Retrying connect to hardware
[12/28/2019, 11:10:58 AM] [ZigBee] Retrying connect to hardware
[12/28/2019, 11:11:05 AM] [ZigBee] Retrying connect to hardware
[12/28/2019, 11:11:12 AM] [ZigBee] Retrying connect to hardware
[12/28/2019, 11:11:18 AM] [ZigBee] ZigBee platform initialized, info:
[12/28/2019, 11:11:18 AM] [ZigBee] ------------------------------------
[12/28/2019, 11:11:18 AM] [ZigBee] channel: 11
[12/28/2019, 11:11:18 AM] [ZigBee] pan id: 0x5430
[12/28/2019, 11:11:18 AM] [ZigBee] extended pan id: 0xdddddddddddddddd
[12/28/2019, 11:11:18 AM] [ZigBee] ieee address: 0x00124b00193e50db
[12/28/2019, 11:11:18 AM] [ZigBee] nwk address: 0
[12/28/2019, 11:11:18 AM] [ZigBee] firmware version: 2.6.3
[12/28/2019, 11:11:18 AM] [ZigBee] firmware revision: 2018090201
[12/28/2019, 11:11:18 AM] [ZigBee] ------------------------------------
[12/28/2019, 11:11:18 AM] [ZigBee] Unrecognized device: 0x00158d0002c65f0d LUMI lumi.light.aqcn02
spinlock: false []
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 1 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 2 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 3 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 4 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 5 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 6 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 7 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 8 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 9 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 10 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 11 of 17
[12/28/2019, 11:11:50 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 12 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 13 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 14 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 15 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 16 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 17 of 17
[12/28/2019, 11:11:51 AM] [ZigBee] Device announced incoming and is added, id: 0x00158d0002c65f0d
[12/28/2019, 11:11:52 AM] [ZigBee] Unrecognized device: 0x00158d0002c65f0d LUMI lumi.light.aqcn02
[12/28/2019, 11:12:18 AM] [ZigBee] [RouterPolling] ping device: 0x00158d0002c65f0d
[12/28/2019, 11:13:18 AM] [ZigBee] [RouterPolling] ping device: 0x00158d0002c65f0d
[12/28/2019, 11:14:18 AM] [ZigBee] [RouterPolling] ping device: 0x00158d0002c65f0d

**Comment by halilaykent** [comment]
[12/28/2019, 2:47:48 PM] [ZigBee] Registered device: 0x00158d0002c65f0d LUMI lumi.light.aqcn02
spinlock: false []
Uncaught Exception TypeError: this.clearTimeout is not a function
    at Characteristic.onCharacteristic.on (/usr/local/lib/node_modules/homebridge-zigbee/lib/devices/lumi.light.aqcn02.js:33:12)
    at Characteristic.emit (events.js:203:15)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
[12/28/2019, 2:47:49 PM] TypeError: this.clearTimeout is not a function
    at Characteristic.onCharacteristic.on (/usr/local/lib/node_modules/homebridge-zigbee/lib/devices/lumi.light.aqcn02.js:33:12)
    at Characteristic.emit (events.js:203:15)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)

**Comment by halilaykent** [comment]
The problem only arises when i try to turn on/off the bulb or change the brightness. Chaning just the color temperature is working perfectly fine
