### ISSUE TITLE
Aqara motion sensor не работает

### ISSUE THREAD

**Issue by daspru** [itsmepetrov/homebridge-zigbee#9]
дано: raspbian lite, homebridge, sprut stick, sensor (http://joxi.ru/xAeBg6jTp89yzr)
добавление проходит, но сенсор не появляется в ХБ и ХК. При срабатывании сенсор в логе ХБ пишет 
`[ZigBee] Received message from unknown device: 0x00158d0002006d6a`

zigbee.db:
`{"id":4,"type":"EndDevice","ieeeAddr":"0x00158d0002006d6a","nwkAddr":64637,"manufId":4151,"epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,1,3,1024,1030,1280,65535],"outClusterList":[0,25],"clusters":{"genBasic":{"dir":{"value":3},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"msIlluminanceMeasurement":{"dir":{"value":1},"attrs":{}},"msOccupancySensing":{"dir":{"value":1},"attrs":{}},"ssIasZone":{"dir":{"value":1},"attrs":{}},"manuSpecificCluster":{"dir":{"value":1},"attrs":{}}}}},"_id":"4WWSpeMKXJkl734q"}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0012013e66","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1541807570,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"91uwy8C01VLH8Cab"}
{"id":3,"type":"Router","ieeeAddr":"0x00158d0002328c4f","nwkAddr":11921,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug","epList":[1,2,3,100],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,1,2,3,4,5,6,10,16],"outClusterList":[10,25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":22,"stackVersion":2,"hwVersion":18,"manufacturerName":"LUMI","modelId":"lumi.plug","dateCode":"02-28-2017","powerSource":1}},"genPowerCfg":{"dir":{"value":1},"attrs":{"mainsVoltage":2244,"mainsAlarmMask":0}},"genDeviceTempCfg":{"dir":{"value":1},"attrs":{"currentTemperature":29,"lowTempThres":55,"highTempThres":60}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0,"lastCfgBy":"0xffffffffffffffff"}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":0}},"genTime":{"dir":{"value":3},"attrs":{}},"genBinaryOutput":{"dir":{"value":1},"attrs":{"activeText":"","inactiveText":"","outOfService":0,"presentValue":0,"statusFlags":0}},"genOta":{"dir":{"value":2},"attrs":{}}}},"2":{"profId":260,"epId":2,"devId":9,"inClusterList":[12],"outClusterList":[4,12],"clusters":{"genGroups":{"dir":{"value":2},"attrs":{}},"genAnalogInput":{"dir":{"value":3},"attrs":{"261":0,"262":0,"maxPresentValue":0,"outOfService":0,"presentValue":0,"statusFlags":0,"applicationType":589824}}}},"3":{"profId":260,"epId":3,"devId":83,"inClusterList":[12],"outClusterList":[12],"clusters":{"genAnalogInput":{"dir":{"value":3},"attrs":{"261":0,"262":0,"maxPresentValue":0,"outOfService":0,"presentValue":0.000027561110982787795,"statusFlags":0,"applicationType":720896}}}},"100":{"profId":260,"epId":100,"devId":263,"inClusterList":[15],"outClusterList":[4,15],"clusters":{"genGroups":{"dir":{"value":2},"attrs":{}},"genBinaryInput":{"dir":{"value":3},"attrs":{}}}}},"_id":"h7H34C7YHKRy4r7V"}
{"$$indexCreated":{"fieldName":"id","unique":true,"sparse":false}}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0012013e66","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1541807702,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"91uwy8C01VLH8Cab"}
{"id":4,"type":"EndDevice","ieeeAddr":"0x00158d0002006d6a","nwkAddr":64637,"manufId":4151,"epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,1,3,1024,1030,1280,65535],"outClusterList":[0,25],"clusters":{"genBasic":{"dir":{"value":3},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"msIlluminanceMeasurement":{"dir":{"value":1},"attrs":{}},"msOccupancySensing":{"dir":{"value":1},"attrs":{}},"ssIasZone":{"dir":{"value":1},"attrs":{}},"manuSpecificCluster":{"dir":{"value":1},"attrs":{}}}}},"_id":"4WWSpeMKXJkl734q"}
{"id":3,"type":"Router","ieeeAddr":"0x00158d0002328c4f","nwkAddr":11921,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug","epList":[1,2,3,100],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,1,2,3,4,5,6,10,16],"outClusterList":[10,25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":22,"stackVersion":2,"hwVersion":18,"manufacturerName":"LUMI","modelId":"lumi.plug","dateCode":"02-28-2017","powerSource":1}},"genPowerCfg":{"dir":{"value":1},"attrs":{"mainsVoltage":2244,"mainsAlarmMask":0}},"genDeviceTempCfg":{"dir":{"value":1},"attrs":{"currentTemperature":29,"lowTempThres":55,"highTempThres":60}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0,"lastCfgBy":"0xffffffffffffffff"}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":0}},"genTime":{"dir":{"value":3},"attrs":{}},"genBinaryOutput":{"dir":{"value":1},"attrs":{"activeText":"","inactiveText":"","outOfService":0,"presentValue":0,"statusFlags":0}},"genOta":{"dir":{"value":2},"attrs":{}}}},"2":{"profId":260,"epId":2,"devId":9,"inClusterList":[12],"outClusterList":[4,12],"clusters":{"genGroups":{"dir":{"value":2},"attrs":{}},"genAnalogInput":{"dir":{"value":3},"attrs":{"261":0,"262":0,"maxPresentValue":0,"outOfService":0,"presentValue":0,"statusFlags":0,"applicationType":589824}}}},"3":{"profId":260,"epId":3,"devId":83,"inClusterList":[12],"outClusterList":[12],"clusters":{"genAnalogInput":{"dir":{"value":3},"attrs":{"261":0,"262":0,"maxPresentValue":0,"outOfService":0,"presentValue":0.000027561110982787795,"statusFlags":0,"applicationType":720896}}}},"100":{"profId":260,"epId":100,"devId":263,"inClusterList":[15],"outClusterList":[4,15],"clusters":{"genGroups":{"dir":{"value":2},"attrs":{}},"genBinaryInput":{"dir":{"value":3},"attrs":{}}}}},"_id":"h7H34C7YHKRy4r7V"}`

Лог установки:
`[2018-11-10 02:15:23] [ZigBee] [PermitJoinAccessory] time left: 108
spinlock: false []
[2018-11-10 02:15:24] [ZigBee] [PermitJoinAccessory] time left: 107
[2018-11-10 02:15:39] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:39] [ZigBee] [PermitJoinAccessory] time left: 92
[2018-11-10 02:15:40] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 1 of 8
[2018-11-10 02:15:40] [ZigBee] [PermitJoinAccessory] time left: 91
[2018-11-10 02:15:40] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:40] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:40] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 2 of 8
[2018-11-10 02:15:41] [ZigBee] [PermitJoinAccessory] time left: 90
[2018-11-10 02:15:42] [ZigBee] [PermitJoinAccessory] time left: 89
[2018-11-10 02:15:43] [ZigBee] [PermitJoinAccessory] time left: 88
[2018-11-10 02:15:44] [ZigBee] [PermitJoinAccessory] time left: 87
[2018-11-10 02:15:45] [ZigBee] [PermitJoinAccessory] time left: 86
[2018-11-10 02:15:46] [ZigBee] [PermitJoinAccessory] time left: 85
[2018-11-10 02:15:46] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 3 of 8
[2018-11-10 02:15:47] [ZigBee] [PermitJoinAccessory] time left: 84
[2018-11-10 02:15:48] [ZigBee] [PermitJoinAccessory] time left: 83
[2018-11-10 02:15:49] [ZigBee] [PermitJoinAccessory] time left: 82
[2018-11-10 02:15:50] [ZigBee] [PermitJoinAccessory] time left: 81
[2018-11-10 02:15:51] [ZigBee] [PermitJoinAccessory] time left: 80
[2018-11-10 02:15:52] [ZigBee] [PermitJoinAccessory] time left: 79
[2018-11-10 02:15:52] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:52] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:53] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 4 of 8
[2018-11-10 02:15:53] [ZigBee] [PermitJoinAccessory] time left: 78
[2018-11-10 02:15:54] [ZigBee] [PermitJoinAccessory] time left: 77
[2018-11-10 02:15:55] [ZigBee] [PermitJoinAccessory] time left: 76
[2018-11-10 02:15:56] [ZigBee] [PermitJoinAccessory] time left: 75
[2018-11-10 02:15:57] [ZigBee] [PermitJoinAccessory] time left: 74
[2018-11-10 02:15:58] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:58] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:15:58] [ZigBee] [PermitJoinAccessory] time left: 73
[2018-11-10 02:15:59] [ZigBee] [PermitJoinAccessory] time left: 72
[2018-11-10 02:16:00] [ZigBee] [PermitJoinAccessory] time left: 71
[2018-11-10 02:16:01] [ZigBee] [PermitJoinAccessory] time left: 70
[2018-11-10 02:16:02] [ZigBee] [PermitJoinAccessory] time left: 69
[2018-11-10 02:16:03] [ZigBee] [PermitJoinAccessory] time left: 68
[2018-11-10 02:16:04] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 5 of 8
[2018-11-10 02:16:04] [ZigBee] [PermitJoinAccessory] time left: 67
[2018-11-10 02:16:05] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:05] [ZigBee] [PermitJoinAccessory] time left: 66
[2018-11-10 02:16:06] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 6 of 8
[2018-11-10 02:16:06] [ZigBee] [PermitJoinAccessory] time left: 65
[2018-11-10 02:16:07] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:07] [ZigBee] [PermitJoinAccessory] time left: 64
[2018-11-10 02:16:08] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 7 of 8
[2018-11-10 02:16:08] [ZigBee] [PermitJoinAccessory] time left: 63
[2018-11-10 02:16:09] [ZigBee] [PermitJoinAccessory] time left: 62
[2018-11-10 02:16:09] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:10] [ZigBee] [PermitJoinAccessory] time left: 61
[2018-11-10 02:16:10] [ZigBee] Join progress: interview endpoint 1 of 1 and cluster 8 of 8
[2018-11-10 02:16:10] [ZigBee] Device announced incoming and is added, id: 0x00158d0002006d6a
[2018-11-10 02:16:12] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:12] [ZigBee] Unrecognized device: 0x00158d0002006d6a undefined undefined
[2018-11-10 02:16:14] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:15] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:15] [ZigBee] Received message from unknown device: 0x00158d0002006d6a
[2018-11-10 02:16:21] [ZigBee] Received message from unknown device: 0x00158d0002006d6a`

**Comment by itsmepetrov** [comment]
Hi @daspru, it looks like your device didn't provide information about mode and manufacturer, or the plugin didn't read this information properly, so you caught such error. I recommend you to try to add this device again, but don't forget to wake up device every 2-3 seconds by pressing on reset button. Also I can recommend you reboot your device (inject and insert battery).

**Comment by itsmepetrov** [comment]
Hi @qavk, it seems like you are doing something wrong, maybe you forgot to wake up your device during pairing? Please read recommendations in previous comment and try again.

**Comment by qavk** [comment]
> Hi @qavk, it seems like you are doing something wrong, maybe you forgot to wake up your device during pairing? Please read recommendations in previous comment and try again.

Да, забыл про это, спасибо) 
Но на этом проблемы не закончились: появилась проблема, как у человека выше..
Сделал, как вы и посоветовали: вытащил батарейку, попробовал привязать заново, получилось раза с третьего после вытаскивания батарейки (устройство привязывалось, но не определялось). Пока пытался подключить датчик движения малинка дважды уходил в ребут, один из них - в бесконечный. Причины падения неизвестны, образ полностью ваш, только к wifi подключился.
До этого подключил розетку, датчик температуры и влажности и кубик - никаких проблем не возникло. Ниже приложу логи. Как я понял из них, стик не мог подключиться к малине и переподключался, а про датчик движения - просто выдавало ошибку, что устройство не определено. 
Расписал поподробнее, может, вам и кому-то еще будет полезно)

`[11/12/2018, 1:23:44 PM] Homebridge is running on port 51826.
[11/12/2018, 1:37:16 PM] [ZigBee] Retrying connect to hardware
[11/12/2018, 1:37:21 PM] [Config] Authentication Disabled
[11/12/2018, 1:37:21 PM] [Config] Console v3.8.11 is listening on port 80.
[11/12/2018, 1:37:23 PM] [ZigBee] Retrying connect to hardware

[11/12/2018, 1:37:30 PM] [ZigBee] Retrying connect to hardware
[11/12/2018, 1:37:37 PM] [ZigBee] Retrying connect to hardware
[11/12/2018, 1:37:44 PM] [ZigBee] error: Error: request timeout
    at CcZnp.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/node_modules/cc-znp/lib/ccznp.js:255:22)
    at Object.onceWrapper (events.js:273:13)
    at CcZnp.emit (events.js:182:13)
    at Timeout.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge-zigbee/node_modules/cc-znp/lib/ccznp.js:234:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[11/12/2018, 1:37:44 PM] [ZigBee] Retrying connect to hardware
[11/12/2018, 1:37:50 PM] [ZigBee] ZigBee platform initialized, info:
[11/12/2018, 1:37:50 PM] [ZigBee] ------------------------------------
[11/12/2018, 1:37:50 PM] [ZigBee] channel: 11
[11/12/2018, 1:37:50 PM] [ZigBee] pan id: 0x0dc6
[11/12/2018, 1:37:50 PM] [ZigBee] extended pan id: 0xdddddddddddddddd
[11/12/2018, 1:37:50 PM] [ZigBee] ieee address: 0x00124b0012023301
[11/12/2018, 1:37:50 PM] [ZigBee] nwk address: 0
[11/12/2018, 1:37:50 PM] [ZigBee] firmware version: 2.6.3
[11/12/2018, 1:37:50 PM] [ZigBee] firmware revision: 2018090201
[11/12/2018, 1:37:50 PM] [ZigBee] ------------------------------------
[11/12/2018, 1:37:51 PM] [ZigBee] Registered device: 0x00158d00028f6faa LUMI lumi.sensor_cube
[11/12/2018, 1:37:51 PM] [ZigBee] Registered device: 0x00158d0002454b6b LUMI lumi.sens
[11/12/2018, 1:37:51 PM] [ZigBee] Registered device: 0x00158d0002468dd3 LUMI lumi.plug
[11/12/2018, 1:37:51 PM] [ZigBee] Unrecognized device: 0x00158d000223c4e6 undefined undefined
[11/12/2018, 1:21:36 PM] [ZigBee] Received message from unknown device: 0x00158d000223c4e6`
